### ISSUE TITLE
Does not work on simple script

### ISSUE THREAD

**Issue by worikgh** [captainbrosset/cleanjs#50]
The script that is
```
let q = 3;
```
fails with `Syntax error line 1 : Syntax error: Missing ; before statement`

**Comment by captainbrosset** [comment]
Sorry about this. The reason is that this tool does not work with `let` and other recent ECMAScript syntax features. I built this tool more than 8 years ago, before these things became used widely.
I am also not maintaining this tool anymore.
So I'll be closing this issue now. 
I would advise looking into other, better, tools such as ESLint and Prettier.
